apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
   matchLabels:
    app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app
          image: georgekc/cicd:latest
          ports:
            - containerPort: 80
